name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the release branch
  # and only when gradle.properties is updated
  push:
    branches: [ release ]
    paths:
      - "version.properties"
    #paths-ignore:
    #  - 'otherModule/**'
  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        id: get_tag_name
        run: ./gen_tag_name.sh

      - name: Create relase page
        if: ${{ success() }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_tag_name.outputs.tag_name }}
          prerelease: true
          commit: release

  PR:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: release-${{ needs.release.outputs.tag_name }}
          title: "[Released] ${{ needs.release.outputs.tag_name }}"
          body: "This PR is generated by automation"
          # TODO change label to awaiting testing
          labels: |
            awaiting testing
          # TODO add default reviewers
          reviewers: |
            Kim-Linhb
          assignees: |
            ${{ github.actor }}
          # TODO add team-reviewers, (team reviewer doesn't work as usual)
          #team-reviewers: broadpos-component




